{% set name = "Mako" %}
{% set version = "1.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 99579a6f39583fa7e5630a28c3c1f440e4e97a414b80372649c0ce338da2ea28

build:
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - importlib-metadata
    - markupsafe >=0.9.2
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata
    - markupsafe >=0.9.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://github.com/sqlalchemy/mako

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
