{% set name = "Mako" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e3a9d388fd00e87043edbe8792f45880ac0114e9c4adc69f6e9bfb2c55e3b11b

build:
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - importlib-metadata
    - markupsafe >=0.9.2
    - pip
  run:
    - python >=3.6
    - importlib-metadata
    - markupsafe >=0.9.2

test:
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://github.com/sqlalchemy/mako

extra:
  recipe-maintainers:
    - pmlandwehr
    - xhochy
