{% set name = "Mako" %}
{% set version = "1.0.11" %}
{% set checksum = "889c7f16d5388092d4c585cf9def19cad089e9f848a7c40e03394553048362a6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  preserve_egg_dir: True
  entry_points:
    - mako-render=mako.cmd:cmdline
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - python
    - pip
    - markupsafe >=0.9.2
    
  run:
    - python
    - markupsafe >=0.9.2

test:
  imports:
    - mako
    - mako.ext
  commands:
    - mako-render --help

about:
  home: http://www.makotemplates.org/
  license_file: LICENSE
  license: MIT
  summary: A super-fast templating language that borrows the best ideas from the existing templating languages.
  doc_url: http://docs.makotemplates.org/en/latest/
  dev_url: https://bitbucket.org/zzzeek/mako/src

extra:
  recipe-maintainers:
    - pmlandwehr
